import { Routes } from '@angular/router';
import { IndexComponent } from '../../index/index.component';
import { PortalAccessComponent } from '../../portal-access/portal-access.component';
import { DashboardComponent } from '../../dashboard/dashboard.component';
import { NotificationsComponent } from '../../notifications/notifications.component';
import { WardMonitoringComponent } from '../../reports/ward-monitoring/ward-monitoring.component';
import { SkipLineComponent } from '../../reports/skip-line/skip-line.component';
import { HaltsComponent } from '../../reports/halts/halts.component';
import { LoginComponent } from '../../login/login.component';
import { LogoutComponent } from '../../logout/logout.component';
import { HouseEntryFormComponent } from '../../house-entry-form/house-entry-form.component';
import { DownloadCollectionReportComponent } from '../../reports/download-collection-report/download-collection-report.component';
import { HouseSearchComponent } from '../../housesearch/housesearch.component';
import { FleetMonitorComponent } from '../../fleet-monitor/fleet-monitor.component';
import { LineStatisticsComponent } from '../../line-statistics/line-statistics.component';
import { LineCardMappingComponent } from '../../house-survey/line-card-mapping/line-card-mapping.component';
import { TimeDistanceComponent } from '../../reports/time-distance/time-distance.component';
import { RealtimeMonitoringComponent } from '../../realtime-monitoring/realtime-monitoring.component';
import { DustbinMonitoringComponent } from '../../dustbin-monitoring/dustbin-monitoring.component';
import { DownloadWardwiseReportComponent } from '../../reports/download-wardwise-report/download-wardwise-report.component';
import { UserListComponent } from "../../Users/user-list/user-list.component";
import { UserAddComponent } from "../../Users/user-add/user-add.component";
import { UserAccessComponent } from "../../Users/user-access/user-access.component";
import { HomeComponent } from '../../home/home.component';
import { HaltReportComponent } from '../../halt-report/halt-report.component';
import { RouteTrackingComponent } from '../../route-tracking/route-tracking.component';
import { WardMonitoringReportComponent } from '../../ward-monitoring-report/ward-monitoring-report.component';
import { FinanceComponent } from '../../finance-report/finance/finance.component';
import { WardReachCostComponent } from '../../finance-report/ward-reach-cost/ward-reach-cost.component';
import { MonthSalaryReportComponent } from '../../finance-report/month-salary-report/month-salary-report.component';
import { ReportsComponent } from '../../reports/reports/reports.component';
import { RemarkReportComponent } from '../../reports/remark-report/remark-report.component';
import { WorkAssignReportComponent } from '../../reports/work-assign-report/work-assign-report.component';
import { PortalServicesComponent } from '../../PortalServices/portal-services/portal-services.component';
import { WardDutyDataComponent } from '../../PortalServices/ward-duty-data/ward-duty-data.component';
import { DustbinAnalysisComponent } from '../../reports/dustbin-analysis/dustbin-analysis.component';
import { CmsComponent } from '../../cms/cms.component';
import { Cms1Component } from '../../cms1/cms1.component';
import { VehicleReportComponent } from '../../reports/vehicle-report/vehicle-report.component';
import { WardTripAnalysisComponent } from '../../reports/ward-trip-analysis/ward-trip-analysis.component';
import { HouseMarkingComponent } from '../../house-survey/house-marking/house-marking.component';
import { HouseMarkingAssignmentComponent } from '../../house-survey/house-marking-assignment/house-marking-assignment.component';
import { EmployeeMarkingComponent } from '../../house-survey/employee-marking/employee-marking.component';
import { WardSurveyAnalysisComponent } from '../../house-survey/ward-survey-analysis/ward-survey-analysis.component';
import { WardSurveySummaryComponent } from '../../house-survey/ward-survey-summary/ward-survey-summary.component';
import { WardMarkingSummaryComponent } from '../../house-survey/ward-marking-summary/ward-marking-summary.component';
import { WardScancardReportComponent } from '../../reports/ward-scancard-report/ward-scancard-report.component';
import { LineMarkerMappingComponent } from '../../house-survey/line-marker-mapping/line-marker-mapping.component';
import { VehicleAssignedComponent } from '../../reports/vehicle-assigned/vehicle-assigned.component';
import { LogBookComponent } from '../../reports/log-book/log-book.component';
import { WardScancardSummaryComponent } from '../../reports/ward-scancard-summary/ward-scancard-summary.component';
import { ChangePasswordComponent } from '../../change-password/change-password.component';
import { VehicleFuelReportComponent } from '../../reports/vehicle-fuel-report/vehicle-fuel-report.component';
import { EmployeePenaltyComponent } from '../../finance-report/employee-penalty/employee-penalty.component';
import { PenaltyPortalServiceComponent } from '../../PortalServices/penalty-portal-service/penalty-portal-service.component';
import { AccountDetailComponent } from '../../salary-management/account-detail/account-detail.component';
import { EmployeeSalaryComponent } from '../../salary-management/employee-salary/employee-salary.component';
import { SalaryHoldingManagementComponent } from '../../salary-management/salary-holding-management/salary-holding-management.component';
import { KmlToJsonComponent } from '../../PortalServices/kml-to-json/kml-to-json.component';
import { SalaryTransactionComponent } from '../../salary-management/salary-transaction/salary-transaction.component';
import { DustbinServiceComponent } from '../../Dustbin/dustbin-service/dustbin-service.component';
import { WardWorkTrackingComponent } from '../../ward-work-tracking/ward-work-tracking.component';
import { StaffAccountDetailComponent } from '../../salary-management/staff-account-detail/staff-account-detail.component';
import { WardWorkPercentageComponent } from '../../PortalServices/ward-work-percentage/ward-work-percentage.component';
import { ChangeLineSurveyedDataComponent } from '../../PortalServices/change-line-surveyed-data/change-line-surveyed-data.component';
import { WardWorkDoneComponent } from '../../reports/ward-work-done/ward-work-done.component';
import { SettingsComponent } from '../../PortalServices/settings/settings.component';
import { EmployeesComponent } from '../../EmployeeManagement/employees/employees.component';
import { SpecialUsersComponent } from '../../EmployeeManagement/special-users/special-users.component';
import { DustbinPlaningComponent } from '../../Dustbin/dustbin-planing/dustbin-planing.component';
import { DustbinWardMappingComponent } from '../../PortalServices/dustbin-ward-mapping/dustbin-ward-mapping.component';
import { LineWeightageComponent } from '../../PortalServices/line-weightage/line-weightage.component';
import { DustbinManageComponent } from '../../Dustbin/dustbin-manage/dustbin-manage.component';
import { RoutesTrackingComponent } from '../../routes-tracking/routes-tracking.component';
import { SalaryCalculationComponent } from '../../salary-management/salary-calculation/salary-calculation.component';
import { DailyFuelReportComponent } from '../../reports/daily-fuel-report/daily-fuel-report.component';
import { SalaryCalculationsComponent } from '../../salary-management/salary-calculations/salary-calculations.component';
import { EmployeeAttendanceComponent } from '../../EmployeeManagement/employee-attendance/employee-attendance.component';
import { MonthlyAttendanceComponent } from '../../EmployeeManagement/monthly-attendance/monthly-attendance.component';
import { DailyWorkDetailComponent } from '../../reports/daily-work-detail/daily-work-detail.component';
import { SupportQueryComponent } from '../../EmployeeManagement/support-query/support-query.component';
import { MonthlyFuelReportComponent } from '../../reports/monthly-fuel-report/monthly-fuel-report.component';
import { ChangeLineMarkerDataComponent } from '../../PortalServices/change-line-marker-data/change-line-marker-data.component';
import { RolesComponent } from '../../user-management/roles/roles.component';
import { RolePageAccessComponent } from '../../user-management/role-page-access/role-page-access.component';
import { MapsComponent } from '../../maps/maps.component';
import { CardMarkerMappingComponent } from '../../Developers/card-marker-mapping/card-marker-mapping.component';
import { ScanCardStatusComponent } from '../../house-survey/scan-card-status/scan-card-status.component';
import { ComplaintListComponent } from '../../complaint-list/complaint-list.component';
import { ScanCardManipulationComponent } from '../../PortalServices/scan-card-manipulation/scan-card-manipulation.component';
import { AddMarkerAgainstCardsComponent } from '../../Developers/add-marker-against-cards/add-marker-against-cards.component';
import { CardScanningReportComponent } from '../../reports/card-scanning-report/card-scanning-report.component';
import { SurveyVerificationComponent } from '../../house-survey/survey-verification/survey-verification.component';
import { SurveyHousesComponent } from '../../house-survey/survey-houses/survey-houses.component';
import { MarkerApprovalTestComponent } from '../../marker-approval-test/marker-approval-test.component';
import { SupervisorReportComponent } from '../../house-survey/supervisor-report/supervisor-report.component';
import { SetNearbyWardComponent } from '../../PortalServices/set-nearby-ward/set-nearby-ward.component';
import { ManageMarkingDataComponent } from '../../Developers/manage-marking-data/manage-marking-data.component';
import { WardwiseScanCardComponent } from '../../wardwise-scan-card/wardwise-scan-card.component';
import { ReviewDutyonImagesComponent } from '../../review-dutyon-images/review-dutyon-images.component';
import { ReviewTripImagesComponent } from '../../reports/review-trip-images/review-trip-images.component';
import { PaymentCollectorComponent } from '../../payment-collector/payment-collector.component';
import { DueAmountReportComponent } from '../../reports/due-amount-report/due-amount-report.component';
import { CollectedAmountReportComponent } from '../../reports/collected-amount-report/collected-amount-report.component';
import { SurveyVerifiedReportComponent } from '../../house-survey/survey-verified-report/survey-verified-report.component';
import { PaymentViaChequeComponent } from '../../reports/payment-via-cheque/payment-via-cheque.component';
import { PaymentViaChequeReportComponent } from '../../reports/payment-via-cheque-report/payment-via-cheque-report.component';
import { CardTransectionDetailComponent } from '../../reports/card-transection-detail/card-transection-detail.component';
import { CardUpdatedHistoryComponent } from '../../reports/card-updated-history/card-updated-history.component';
import { DailyPaymentReportComponent } from '../../reports/daily-payment-report/daily-payment-report.component';
import { MonthlyPaymentReportComponent } from '../../reports/monthly-payment-report/monthly-payment-report.component';
import { EntityPaymentReportComponent } from '../../reports/entity-payment-report/entity-payment-report.component';
import { WardRoadDetailComponent } from '../../house-survey/ward-road-detail/ward-road-detail.component';
import { UpdateSurveyorVirtualComponent } from '../../Developers/update-surveyor-virtual/update-surveyor-virtual.component';
import { NonSalariedCalculationComponent } from '../../salary-management/non-salaried-calculation/non-salaried-calculation.component';
import { VehicleTrackingComponent } from '../../VTS/vehicle-tracking/vehicle-tracking.component';
import { VheicleCurrentInfoComponent } from '../../VTS/vheicle-current-info/vheicle-current-info.component';
import { SetMarkerImagesComponent } from '../../Developers/set-marker-images/set-marker-images.component';
import { PaymentViaNeftComponent } from '../../reports/payment-via-neft/payment-via-neft.component';
import { PaymentViaNeftReportComponent } from '../../reports/payment-via-neft-report/payment-via-neft-report.component';
import { RemoveDeletedScancardsComponent } from '../../Developers/remove-deleted-scancards/remove-deleted-scancards.component';
import { PenaltyReviewComponent } from '../../PortalServices/penalty-review/penalty-review.component';
import { PaymentViaCitizenappComponent } from '../../reports/payment-via-citizenapp/payment-via-citizenapp.component';
import { PageLoadHistoryComponent } from '../../page-load-history/page-load-history.component';
import { DatabaseUtilizationComponent } from '../../database-utilization/database-utilization.component';
import { SecondaryCollectionMonitoringComponent } from '../../secondary-collection-monitoring/secondary-collection-monitoring.component';
import { SecondaryCollectionAnalysisComponent } from '../../secondary-collection-analysis/secondary-collection-analysis.component';
import { SecondaryCollectionPlaningComponent } from '../../secondary-collection-planing/secondary-collection-planing.component';
import { SecondaryCollectionServiceComponent } from '../../secondary-collection-service/secondary-collection-service.component';
import { SecondaryCollectionManageComponent } from '../../secondary-collection-manage/secondary-collection-manage.component';
import { EntityModificationComponent } from '../../entity-modification/entity-modification.component';
import { PaymentCollectorTrackingComponent } from '../../reports/payment-collector-tracking/payment-collector-tracking.component';
import { ErrorPageComponent } from '../../error-page/error-page.component';
import { SecondaryCollectionWardMappingComponent } from '../../PortalServices/secondary-collection-ward-mapping/secondary-collection-ward-mapping.component';
import { MonthlyWorkReportComponent } from '../../reports/monthly-work-report/monthly-work-report.component';
import { WebPortalSettingComponent } from '../../PortalServices/web-portal-setting/web-portal-setting.component';
import { WardRouteTrackingComponent } from '../../ward-route-tracking/ward-route-tracking.component';
import { WardDutyOnComponent } from '../../PortalServices/ward-duty-on/ward-duty-on.component';



// Jaipur-Greater

import { GarbageCaptureAnalysisComponent } from '../../VTS/garbage-capture-analysis/garbage-capture-analysis.component';
import { VtsReportComponent } from '../../VTS/vts-report/vts-report.component';
import { VtsMonthlyReportComponent } from '../../VTS/vts-monthly-report/vts-monthly-report.component';
import { VtsRouteComponent } from '../../VTS/vts-route/vts-route.component';
import { CreateRoutesComponent } from '../../VTS/create-routes/create-routes.component';
import { UploadRouteExcelComponent } from '../../VTS/upload-route-excel/upload-route-excel.component';
import { BvgRoutesComponent } from '../../VTS/bvg-routes/bvg-routes.component';
import { VtsAnalysisComponent } from '../../VTS/vts-analysis/vts-analysis.component';
import { PenaltySummaryComponent } from '../../VTS/penalty-summary/penalty-summary.component';
import { FieldExecutiveTrackingComponent } from '../../VTS/field-executive-tracking/field-executive-tracking.component';
import { ShowRouteComponent } from '../../VTS/show-route/show-route.component';
import { FieldExecutiveAttendanceComponent } from '../../VTS/field-executive-attendance/field-executive-attendance.component';
import { FeDailyWorkReportComponent } from '../../VTS/fe-daily-work-report/fe-daily-work-report.component';


// BI Dashboard

import { AssetsDashboardComponent } from '../../reports/assets-dashboard/assets-dashboard.component';
import { ComplaintDashboardComponent } from '../../reports/complaint-dashboard/complaint-dashboard.component';
import { FuelDashboardComponent } from '../../reports/fuel-dashboard/fuel-dashboard.component';
import { BikeFuelDashboardComponent } from '../../reports/bike-fuel-dashboard/bike-fuel-dashboard.component';
import { MonitoringDashboardComponent } from '../../reports/monitoring-dashboard/monitoring-dashboard.component';
import { SopDashboardComponent } from '../../reports/sop-dashboard/sop-dashboard.component';
import { VehicleAnalysisDashboardComponent } from '../../reports/vehicle-analysis-dashboard/vehicle-analysis-dashboard.component';
import { UccChargeCollectionDashboardComponent } from '../../reports/ucc-charge-collection-dashboard/ucc-charge-collection-dashboard.component';
import { VehicleMaintenanceDashboardComponent } from '../../reports/vehicle-maintenance-dashboard/vehicle-maintenance-dashboard.component';
import { CameraVtsDashboardComponent } from '../../reports/camera-vts-dashboard/camera-vts-dashboard.component';
import { EmpMonitoringDashboardComponent } from '../../reports/emp-monitoring-dashboard/emp-monitoring-dashboard.component';


export const AdminLayoutRoutes: Routes = [
    { path: 'index', component: IndexComponent },
    { path: 'index#home', component: IndexComponent },
    { path: 'index#about', component: IndexComponent },
    { path: 'index#how-we-work', component: IndexComponent },
    { path: 'index#services', component: IndexComponent },
    { path: 'index#gallery', component: IndexComponent },
    { path: 'portal-access', component: PortalAccessComponent },
    { path: 'login', component: LoginComponent },
    { path: 'logout', component: LogoutComponent },
    { path: 'complaint-list', component: ComplaintListComponent },
    { path: 'marker-approval-test', component: MarkerApprovalTestComponent },
    { path: 'supervisor-report', component: SupervisorReportComponent },


    { path: 'jaipur-greater/:id/vts-report', component: VtsReportComponent },
    { path: 'jaipur-greater/:id/vts-monthly-report', component: VtsMonthlyReportComponent },    
    { path: 'jaipur-greater/:id/vts-route', component: VtsRouteComponent },
    { path: 'jaipur-greater/:id/create-routes', component: CreateRoutesComponent },
    { path: 'jaipur-greater/:id/upload-route-excel', component: UploadRouteExcelComponent },
    { path: 'jaipur-greater/:id/bvg-routes', component: BvgRoutesComponent },
    { path: 'jaipur-greater/:id/vts-analysis', component: VtsAnalysisComponent },
    { path: 'jaipur-greater/:id/penalty-summary', component: PenaltySummaryComponent },
    { path: 'jaipur-greater/:id/field-executive-tracking', component: FieldExecutiveTrackingComponent },
    { path: 'jaipur-greater/:id/show-route', component: ShowRouteComponent },
    { path: 'jaipur-greater/:id/field-executive-attendance', component: FieldExecutiveAttendanceComponent },
    { path: 'jaipur-greater/:id/fe-daily-work-report', component: FeDailyWorkReportComponent },
    { path: 'jaipur-greater/:id/garbage-capture-analysis', component: GarbageCaptureAnalysisComponent },
    { path: 'jaipur-greater/:id/card-transaction-detail', component: CardTransectionDetailComponent },
    { path: 'jaipur-greater/:id/monthly-attendance-report', component: MonthlyAttendanceComponent },
        
    { path: ':cityId/home', component: HomeComponent },
    { path: ':cityId/something-wrong', component: ErrorPageComponent },
    { path: ':cityId/account-detail', component: AccountDetailComponent },
    { path: ':cityId/change-password', component: ChangePasswordComponent },
    { path: ':cityId/dashboard', component: DashboardComponent },
    { path: ':cityId/notifications', component: NotificationsComponent },
    { path: ':cityId/ward-report', component: WardMonitoringComponent },
    { path: ':cityId/skip-lines', component: SkipLineComponent },
    { path: ':cityId/halts', component: HaltsComponent },
    { path: ':cityId/login', component: LoginComponent },
    { path: ':cityId/logout', component: LogoutComponent },
    { path: ':cityId/hsfrm', component: HouseEntryFormComponent },
    { path: ':cityId/download-report', component: DownloadCollectionReportComponent },
    { path: ':cityId/housesearch', component: HouseSearchComponent },
    { path: ':cityId/fleet-monitor', component: FleetMonitorComponent },
    { path: ':cityId/line-statistics', component: LineStatisticsComponent },
    { path: ':cityId/line-card-mapping', component: LineCardMappingComponent },
    { path: ':cityId/line-card-mapping/:id', component: LineCardMappingComponent },
    { path: ':cityId/time-distance', component: TimeDistanceComponent },
    { path: ':cityId/realtime-monitoring', component: RealtimeMonitoringComponent },
    { path: ':cityId/dustbin-monitoring', component: DustbinMonitoringComponent },
    { path: ':cityId/download-ward-reports', component: DownloadWardwiseReportComponent },
    { path: ':cityId/users', component: UserListComponent },
    { path: ':cityId/useradd/:id', component: UserAddComponent },
    { path: ':cityId/useradd', component: UserAddComponent },
    { path: ':cityId/useracess/:id', component: UserAccessComponent },
    { path: ':cityId/halt-report', component: HaltReportComponent },
    { path: ':cityId/route-tracking/:id1', component: RouteTrackingComponent },
    { path: ':cityId/route-tracking', component: RouteTrackingComponent },
    { path: ':cityId/ward-monitoring-report', component: WardMonitoringReportComponent },
    { path: ':cityId/finance', component: FinanceComponent },
    { path: ':cityId/ward-reach-cost', component: WardReachCostComponent },
    { path: ':cityId/month-salary-report', component: MonthSalaryReportComponent },
    { path: ':cityId/reports', component: ReportsComponent },
    { path: ':cityId/remark-report', component: RemarkReportComponent },
    { path: ':cityId/work-assign-report', component: WorkAssignReportComponent },
    { path: ':cityId/portal-services', component: PortalServicesComponent },
    { path: ':cityId/ward-duty-data', component: WardDutyDataComponent },
    { path: ':cityId/dustbin-analysis', component: DustbinAnalysisComponent },
    { path: ':cityId/cms/:id', component: CmsComponent },
    { path: ':cityId/cms1', component: Cms1Component },
    { path: ':cityId/vehicle-report', component: VehicleReportComponent },
    { path: ':cityId/ward-trip-analysis', component: WardTripAnalysisComponent },
    { path: ':cityId/house-marking', component: HouseMarkingComponent },
    { path: ':cityId/house-marking/:id1', component: HouseMarkingComponent },
    { path: ':cityId/house-marking-assignment', component: HouseMarkingAssignmentComponent },
    { path: ':cityId/employee-marking', component: EmployeeMarkingComponent },
    { path: ':cityId/ward-survey-analysis', component: WardSurveyAnalysisComponent },
    { path: ':cityId/ward-survey-analysis/:id1', component: WardSurveyAnalysisComponent },
    { path: ':cityId/ward-survey-summary', component: WardSurveySummaryComponent },
    { path: ':cityId/ward-marking-summary', component: WardMarkingSummaryComponent },
    { path: ':cityId/ward-scancard-report', component: WardScancardReportComponent },
    { path: ':cityId/line-marker-mapping', component: LineMarkerMappingComponent },
    { path: ':cityId/vehicle-assigned', component: VehicleAssignedComponent },
    { path: ':cityId/log-book', component: LogBookComponent },
    { path: ':cityId/ward-scancard-summary', component: WardScancardSummaryComponent },
    { path: ':cityId/employee-penalty', component: EmployeePenaltyComponent },
    { path: ':cityId/penalty-portal-service', component: PenaltyPortalServiceComponent },
    { path: ':cityId/employee-salary', component: EmployeeSalaryComponent },
    { path: ':cityId/salary-holding-management', component: SalaryHoldingManagementComponent },
    { path: ':cityId/kml-to-json', component: KmlToJsonComponent },
    { path: ':cityId/salary-transaction', component: SalaryTransactionComponent },
    { path: ':cityId/dustbin-service', component: DustbinServiceComponent },
    { path: ':cityId/ward-work-tracking', component: WardWorkTrackingComponent },
    { path: ':cityId/ward-work-tracking/:id', component: WardWorkTrackingComponent },
    { path: ':cityId/staff-account-detail', component: StaffAccountDetailComponent },
    { path: ':cityId/ward-work-percentage', component: WardWorkPercentageComponent },
    { path: ':cityId/change-line-surveyed-data', component: ChangeLineSurveyedDataComponent },
    { path: ':cityId/ward-work-done', component: WardWorkDoneComponent },
    { path: ':cityId/settings', component: SettingsComponent },
    { path: ':cityId/employees', component: EmployeesComponent },
    { path: ':cityId/special-users', component: SpecialUsersComponent },
    { path: ':cityId/dustbin-planing', component: DustbinPlaningComponent },
    { path: ':cityId/dustbin-ward-mapping', component: DustbinWardMappingComponent },
    { path: ':cityId/line-weightage', component: LineWeightageComponent },
    { path: ':cityId/dustbin-manage', component: DustbinManageComponent },
    { path: ':cityId/routes-tracking', component: RoutesTrackingComponent },
    { path: ':cityId/routes-tracking/:id', component: RoutesTrackingComponent },
    { path: ':cityId/salary-calculation', component: SalaryCalculationComponent },
    { path: ':cityId/daily-fuel-report', component: DailyFuelReportComponent },
    { path: ':cityId/salary-calculations', component: SalaryCalculationsComponent },
    { path: ':cityId/employee-attendance', component: EmployeeAttendanceComponent },
    { path: ':cityId/daily-work-detail', component: DailyWorkDetailComponent },
    { path: ':cityId/support-query', component: SupportQueryComponent },
    { path: ':cityId/monthly-fuel-report', component: MonthlyFuelReportComponent },
    { path: ':cityId/role-page-access/:id', component: RolePageAccessComponent },
    { path: ':cityId/assets-dashboard', component: AssetsDashboardComponent },
    { path: ':cityId/complaint-dashboard', component: ComplaintDashboardComponent },
    { path: ':cityId/fuel-dashboard', component: FuelDashboardComponent },
    { path: ':cityId/bike-fuel-dashboard', component: BikeFuelDashboardComponent },
    { path: ':cityId/monitoring-dashboard', component: MonitoringDashboardComponent },
    { path: ':cityId/sop-dashboard', component: SopDashboardComponent },
    { path: ':cityId/vehicle-analysis-dashboard', component: VehicleAnalysisDashboardComponent },
    { path: ':cityId/ucc-charge-collection-dashboard', component: UccChargeCollectionDashboardComponent },
    { path: ':cityId/vehicle-maintenance-dashboard', component: VehicleMaintenanceDashboardComponent },
    { path: ':cityId/camera-vts-dashboard', component: CameraVtsDashboardComponent },
    { path: ':cityId/emp-monitoring-dashboard', component: EmpMonitoringDashboardComponent },


    { path: ':cityId/:id/home', component: HomeComponent },
    { path: ':cityId/:id/dashboard', component: DashboardComponent },
    { path: ':cityId/:id/notifications', component: NotificationsComponent },
    { path: ':cityId/:id/ward-report', component: WardMonitoringComponent },
    { path: ':cityId/:id/skip-lines', component: SkipLineComponent },
    { path: ':cityId/:id/halts', component: HaltsComponent },
    { path: ':cityId/:id/login', component: LoginComponent },
    { path: ':cityId/:id/logout', component: LogoutComponent },
    { path: ':cityId/:id/hsfrm', component: HouseEntryFormComponent },
    { path: ':cityId/:id/download-report', component: DownloadCollectionReportComponent },
    { path: ':cityId/:id/housesearch', component: HouseSearchComponent },
    { path: ':cityId/:id/fleet-monitor', component: FleetMonitorComponent },
    { path: ':cityId/:id/line-statistics', component: LineStatisticsComponent },
    { path: ':cityId/:id/line-card-mapping', component: LineCardMappingComponent },
    { path: ':cityId/:id/line-card-mapping/:id', component: LineCardMappingComponent },
    { path: ':cityId/:id/time-distance', component: TimeDistanceComponent },
    { path: ':cityId/:id/realtime-monitoring', component: RealtimeMonitoringComponent },
    { path: ':cityId/:id/dustbin-monitoring', component: DustbinMonitoringComponent },
    { path: ':cityId/:id/download-ward-reports', component: DownloadWardwiseReportComponent },
    { path: ':cityId/:id/users', component: UserListComponent },
    { path: ':cityId/:id/useradd/:id', component: UserAddComponent },
    { path: ':cityId/:id/useradd', component: UserAddComponent },
    { path: ':cityId/:id/useracess/:id', component: UserAccessComponent },
    { path: ':cityId/:id/halt-report', component: HaltReportComponent },
    { path: ':cityId/:id/route-tracking/:id1', component: RouteTrackingComponent },
    { path: ':cityId/:id/route-tracking', component: RouteTrackingComponent },
    { path: ':cityId/:id/ward-monitoring-report', component: WardMonitoringReportComponent },
    { path: ':cityId/:id/finance', component: FinanceComponent },
    { path: ':cityId/:id/ward-reach-cost', component: WardReachCostComponent },
    { path: ':cityId/:id/month-salary-report', component: MonthSalaryReportComponent },
    { path: ':cityId/:id/reports', component: ReportsComponent },
    { path: ':cityId/:id/remark-report', component: RemarkReportComponent },
    { path: ':cityId/:id/work-assign-report', component: WorkAssignReportComponent },
    { path: ':cityId/:id/portal-services', component: PortalServicesComponent },
    { path: ':cityId/:id/ward-duty-data', component: WardDutyDataComponent },
    { path: ':cityId/:id/dustbin-analysis', component: DustbinAnalysisComponent },
    { path: ':cityId/:id/cms/:id', component: CmsComponent },
    { path: ':cityId/:id/cms1', component: Cms1Component },
    { path: ':cityId/:id/vehicle-report', component: VehicleReportComponent },
    { path: ':cityId/:id/ward-trip-analysis', component: WardTripAnalysisComponent },
    { path: ':cityId/:id/house-marking', component: HouseMarkingComponent },
    { path: ':cityId/:id/house-marking/:id1', component: HouseMarkingComponent },
    { path: ':cityId/:id/house-marking-assignment', component: HouseMarkingAssignmentComponent },
    { path: ':cityId/:id/employee-marking', component: EmployeeMarkingComponent },
    { path: ':cityId/:id/ward-survey-analysis', component: WardSurveyAnalysisComponent },
    { path: ':cityId/:id/ward-survey-analysis/:id1', component: WardSurveyAnalysisComponent },
    { path: ':cityId/:id/ward-survey-summary', component: WardSurveySummaryComponent },
    { path: ':cityId/:id/ward-marking-summary', component: WardMarkingSummaryComponent },
    { path: ':cityId/:id/ward-scancard-report', component: WardScancardReportComponent },
    { path: ':cityId/:id/line-marker-mapping', component: LineMarkerMappingComponent },
    { path: ':cityId/:id/vehicle-assigned', component: VehicleAssignedComponent },
    { path: ':cityId/:id/log-book', component: LogBookComponent },
    { path: ':cityId/:id/ward-scancard-summary', component: WardScancardSummaryComponent },
    { path: ':cityId/:id/change-password', component: ChangePasswordComponent },
    { path: ':cityId/:id/vehicle-fuel-report', component: VehicleFuelReportComponent },
    { path: ':cityId/:id/employee-penalty', component: EmployeePenaltyComponent },
    { path: ':cityId/:id/penalty-portal-service', component: PenaltyPortalServiceComponent },
    { path: ':cityId/:id/account-detail', component: AccountDetailComponent },
    { path: ':cityId/:id/employee-salary', component: EmployeeSalaryComponent },
    { path: ':cityId/:id/salary-holding-management', component: SalaryHoldingManagementComponent },
    { path: ':cityId/:id/kml-to-json', component: KmlToJsonComponent },
    { path: ':cityId/:id/salary-transaction', component: SalaryTransactionComponent },
    { path: ':cityId/:id/dustbin-service', component: DustbinServiceComponent },
    { path: ':cityId/:id1/ward-work-tracking', component: WardWorkTrackingComponent },
    { path: ':cityId/:id1/ward-work-tracking/:id', component: WardWorkTrackingComponent },
    { path: ':cityId/:id/staff-account-detail', component: StaffAccountDetailComponent },
    { path: ':cityId/:id/ward-work-percentage', component: WardWorkPercentageComponent },
    { path: ':cityId/:id/change-line-surveyed-data', component: ChangeLineSurveyedDataComponent },
    { path: ':cityId/:id/ward-work-done', component: WardWorkDoneComponent },
    { path: ':cityId/:id/settings', component: SettingsComponent },
    { path: ':cityId/:id/employees', component: EmployeesComponent },
    { path: ':cityId/:id/special-users', component: SpecialUsersComponent },
    { path: ':cityId/:id/dustbin-planing', component: DustbinPlaningComponent },
    { path: ':cityId/:id/dustbin-ward-mapping', component: DustbinWardMappingComponent },
    { path: ':cityId/:id/line-weightage', component: LineWeightageComponent },
    { path: ':cityId/:id/dustbin-manage', component: DustbinManageComponent },
    { path: ':cityId/:id/routes-tracking', component: RoutesTrackingComponent },
    { path: ':cityId/:id1/routes-tracking/:id', component: RoutesTrackingComponent },
    { path: ':cityId/:id/salary-calculation', component: SalaryCalculationComponent },
    { path: ':cityId/:id/daily-fuel-report', component: DailyFuelReportComponent },
    { path: ':cityId/:id/salary-calculations', component: SalaryCalculationsComponent },
    { path: ':cityId/:id/employee-attendance', component: EmployeeAttendanceComponent },
    { path: ':cityId/:id/daily-work-detail', component: DailyWorkDetailComponent },
    { path: ':cityId/:id/support-query', component: SupportQueryComponent },
    { path: ':cityId/:id/monthly-fuel-report', component: MonthlyFuelReportComponent },
    { path: ':cityId/:id/change-line-marker-data', component: ChangeLineMarkerDataComponent },
    { path: ':cityId/:id/roles', component: RolesComponent },
    { path: ':cityId/:id/maps', component: MapsComponent },
    { path: ':cityId/:id/card-marker-mapping', component: CardMarkerMappingComponent },
    { path: ':cityId/:id/scan-card-status', component: ScanCardStatusComponent },
    { path: ':cityId/:id/complaint-list', component: ComplaintListComponent },
    { path: ':cityId/:id/scan-card-manipulation', component: ScanCardManipulationComponent },
    { path: ':cityId/:id/add-marker-against-cards', component: AddMarkerAgainstCardsComponent },
    { path: ':cityId/:id/card-scanning-report', component: CardScanningReportComponent },
    { path: ':cityId/:id/survey-verification', component: SurveyVerificationComponent },
    { path: ':cityId/:id/survey-houses', component: SurveyHousesComponent },
    { path: ':cityId/:id/marker-approval-test', component: MarkerApprovalTestComponent },
    { path: ':cityId/:id/supervisor-report', component: SupervisorReportComponent },
    { path: ':cityId/:id/set-nearby-ward', component: SetNearbyWardComponent },
    { path: ':cityId/:id/manage-marking-data', component: ManageMarkingDataComponent },
    { path: ':cityId/:id/wardwise-scan-card', component: WardwiseScanCardComponent },
    { path: ':cityId/:id/review-dutyon-images', component: ReviewDutyonImagesComponent },
    { path: ':cityId/:id/review-trip-images', component: ReviewTripImagesComponent },
    { path: ':cityId/:id/payment-collector', component: PaymentCollectorComponent },
    { path: ':cityId/:id/due-amount-report', component: DueAmountReportComponent },
    { path: ':cityId/:id/collected-amount-report', component: CollectedAmountReportComponent },
    { path: ':cityId/:id/survey-verified-report', component: SurveyVerifiedReportComponent },
    { path: ':cityId/:id/payment-via-cheque', component: PaymentViaChequeComponent },
    { path: ':cityId/:id/payment-via-cheque-report', component: PaymentViaChequeReportComponent },
    { path: ':cityId/:id/card-transaction-detail', component: CardTransectionDetailComponent },
    { path: ':cityId/:id/card-updated-history', component: CardUpdatedHistoryComponent },
    { path: ':cityId/:id/daily-payment-report', component: DailyPaymentReportComponent },
    { path: ':cityId/:id/monthly-payment-report', component: MonthlyPaymentReportComponent },
    { path: ':cityId/:id/entity-payment-report', component: EntityPaymentReportComponent },
    { path: ':cityId/:id/ward-road-detail', component: WardRoadDetailComponent },
    { path: ':cityId/:id/update-surveyor-virtual', component: UpdateSurveyorVirtualComponent },
    { path: ':cityId/:id/non-salaried-calculation', component: NonSalariedCalculationComponent },
    { path: ':cityId/:id/vheicle-current-info', component: VheicleCurrentInfoComponent },
    { path: ':cityId/:id/payment-via-neft', component: PaymentViaNeftComponent },
    { path: ':cityId/:id/payment-via-neft-report', component: PaymentViaNeftReportComponent },
    { path: ':cityId/:id/penalty-review', component: PenaltyReviewComponent },
    { path: ':cityId/:id/monthly-attendance-report', component: MonthlyAttendanceComponent },
    { path: ':cityId/:id/payment-via-citizenapp', component: PaymentViaCitizenappComponent },
    { path: ':cityId/:id/page-load-history', component: PageLoadHistoryComponent },
    { path: ':cityId/:id/database-utilization', component: DatabaseUtilizationComponent },
    { path: ':cityId/:id/open-depot-monitoring', component: SecondaryCollectionMonitoringComponent },
    { path: ':cityId/:id/open-depot-analysis', component: SecondaryCollectionAnalysisComponent },
    { path: ':cityId/:id/open-depot-planing', component: SecondaryCollectionPlaningComponent },
    { path: ':cityId/:id/open-depot-service', component: SecondaryCollectionServiceComponent },
    { path: ':cityId/:id/open-depot-manage', component: SecondaryCollectionManageComponent },
    { path: ':cityId/:id/entity-modification', component: EntityModificationComponent },
    { path: ':cityId/:id/payment-collector-tracking', component: PaymentCollectorTrackingComponent },
    { path: ':cityId/:id/open-depot-ward-mapping', component: SecondaryCollectionWardMappingComponent },
    { path: ':cityId/:id/monthly-ward-report', component: MonthlyWorkReportComponent },
    { path: ':cityId/:id/assets-dashboard', component: AssetsDashboardComponent },
    { path: ':cityId/:id/complaint-dashboard', component: ComplaintDashboardComponent },
    { path: ':cityId/:id/fuel-dashboard', component: FuelDashboardComponent },
    { path: ':cityId/:id/bike-fuel-dashboard', component: BikeFuelDashboardComponent },
    { path: ':cityId/:id/monitoring-dashboard', component: MonitoringDashboardComponent },
    { path: ':cityId/:id/sop-dashboard', component: SopDashboardComponent },
    { path: ':cityId/:id/vehicle-analysis-dashboard', component: VehicleAnalysisDashboardComponent },
    { path: ':cityId/:id/ucc-charge-collection-dashboard', component: UccChargeCollectionDashboardComponent },
    { path: ':cityId/:id/vehicle-maintenance-dashboard', component: VehicleMaintenanceDashboardComponent },
    { path: ':cityId/:id/camera-vts-dashboard', component: CameraVtsDashboardComponent },
    { path: ':cityId/:id/emp-monitoring-dashboard', component: EmpMonitoringDashboardComponent },
    { path: ':cityId/:id/web-portal-setting', component: WebPortalSettingComponent },
    { path: ':cityId/:id/ward-route-tracking', component: WardRouteTrackingComponent },
    { path: ':cityId/ward-route-tracking/:id1', component: WardRouteTrackingComponent },
    { path: ':cityId/ward-route-tracking', component: WardRouteTrackingComponent },
    { path: ':cityId/:id/ward-duty-on', component: WardDutyOnComponent },
    

]; 
